# Generated by Django 3.0 on 2026-01-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_copy_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name': 'Letting', 'verbose_name_plural': 'Lettings'},
        ),
    ]
